### ISSUE TITLE
Fix list of plugins

### ISSUE THREAD

**Issue by edsiper** [alexandreteles/monkeyServer#1]
Monkey 1.5.5 do not have plugins: liana_ssl or palm. Instead of liana_ssl please use polarssl

**Comment by alexandreteles** [comment]
Fixed.

**Comment by edsiper** [comment]
still present on:
- monkeyServer_embedded.sh
- monkeyServer_nosql.sh

**Comment by alexandreteles** [comment]
Just corrected this on the script and updated all the references of PolarSSL to mbedTLS.
